# Generated by Django 2.2.28 on 2025-03-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
